ARG version
FROM almalinux:${version:-8}
#RUN cat /etc/*release
ARG COURSE=Docker
ARG TRAINER=Sivakumar
ENV DURATION=120Hrs
RUN echo "course is: ${COURSE},Trainer is: ${TRAINER},Duration is: ${DURATION}"
CMD ["sleep","100"]
